"""Fair Influence Maximization research package."""

from .baselines import BaselineResult, run_baseline, run_baselines
from .community_detection import (
    CommunityDetectionResult,
    CommunityQualityMetrics,
    CommunityStats,
    CommunityValidationReport,
    choose_communities,
    compute_community_quality_metrics,
    detect_communities,
    format_community_debug_report,
    get_community_stats,
    get_community_sizes,
    get_node_community,
    get_nodes_in_community,
    sample_community,
    sample_candidate_nodes_by_community,
    sample_node_from_community,
    score_communities_by_size,
    validate_communities,
    validate_community_assignments,
)
from .config import DatasetConfig
from .data_loader import (
    LoadedDataset,
    ProtectedGroupReport,
    builtin_dataset_exists,
    derive_community_id_protected_attribute,
    format_phase1_report,
    load_dataset_config_file,
    load_dataset,
    resolve_dataset_config,
    resolve_builtin_dataset,
    verify_protected_groups,
    verify_dataset_phase1,
)
from .diffusion import (
    DEFAULT_DIFFUSION_MODEL,
    DiffusionResult,
    SUPPORTED_DIFFUSION_MODELS,
    simulate_independent_cascade,
    simulate_independent_cascade_once,
    validate_diffusion_model,
)
from .evaluation import SeedSetEvaluation, compute_f_score, evaluate_seed_set
from .embeddings import (
    BenchmarkRunResult,
    EmbeddingFrameworkError,
    EmbeddingResult,
    GraphEmbeddingModel,
    OptionalDependencyError,
    PreparedFeatures,
    UnsupportedGraphTypeError,
    available_embedding_methods,
    available_evaluation_tasks,
    create_embedding_model,
    evaluate_embedding_benchmark,
    evaluate_embedding_result,
    evaluation_result_columns,
    prepare_benchmark_features,
    resolve_evaluation_tasks,
    resolve_method_names,
    run_embedding_benchmark,
    run_embedding_method,
)
from .experiment_runner import ExperimentSettings, run_experiment, run_loaded_experiment
from .feature_extraction import compute_node_features, compute_structural_node_scores
from .fairness import (
    FairnessMetrics,
    compute_dcv,
    compute_normalized_group_spread,
    compute_soft_mf,
    compute_strict_mf,
    evaluate_fairness,
)
from .gnn_training import GNNTrainingResult, train_gnn_node_utility_model
from .hybrid_optimizer import CandidateEvaluation, HybridOptimizationResult, HybridSIEAConfig, HybridSIEAOptimizer
from .label_generation import NodeUtilityLabelResult, generate_singleton_node_utility_labels
from .ml_training import MLTrainingResult, select_ml_candidate_nodes, train_node_utility_model
from .node2vec_embeddings import (
    Node2VecConfig,
    Node2VecEmbeddingResult,
    build_node2vec_cache_path,
    generate_node2vec_embeddings,
    transform_node2vec_embeddings,
)
from .ris_guidance import RISConfig, RISGuidanceResult, generate_ris_guidance

__all__ = [
    "BaselineResult",
    "CandidateEvaluation",
    "CommunityDetectionResult",
    "CommunityQualityMetrics",
    "CommunityStats",
    "CommunityValidationReport",
    "DEFAULT_DIFFUSION_MODEL",
    "DatasetConfig",
    "LoadedDataset",
    "ProtectedGroupReport",
    "choose_communities",
    "create_embedding_model",
    "DiffusionResult",
    "detect_communities",
    "EmbeddingFrameworkError",
    "EmbeddingResult",
    "ExperimentSettings",
    "evaluate_seed_set",
    "available_embedding_methods",
    "available_evaluation_tasks",
    "evaluate_embedding_benchmark",
    "evaluate_embedding_result",
    "FairnessMetrics",
    "GraphEmbeddingModel",
    "GNNTrainingResult",
    "SeedSetEvaluation",
    "compute_f_score",
    "compute_dcv",
    "compute_community_quality_metrics",
    "compute_node_features",
    "compute_normalized_group_spread",
    "compute_structural_node_scores",
    "compute_soft_mf",
    "compute_strict_mf",
    "evaluate_fairness",
    "format_phase1_report",
    "format_community_debug_report",
    "get_community_stats",
    "get_community_sizes",
    "get_node_community",
    "get_nodes_in_community",
    "HybridOptimizationResult",
    "HybridSIEAConfig",
    "HybridSIEAOptimizer",
    "builtin_dataset_exists",
    "derive_community_id_protected_attribute",
    "load_dataset",
    "load_dataset_config_file",
    "MLTrainingResult",
    "NodeUtilityLabelResult",
    "Node2VecConfig",
    "Node2VecEmbeddingResult",
    "OptionalDependencyError",
    "PreparedFeatures",
    "prepare_benchmark_features",
    "evaluation_result_columns",
    "run_experiment",
    "run_embedding_benchmark",
    "run_embedding_method",
    "run_loaded_experiment",
    "resolve_evaluation_tasks",
    "resolve_dataset_config",
    "resolve_method_names",
    "resolve_builtin_dataset",
    "RISConfig",
    "RISGuidanceResult",
    "BenchmarkRunResult",
    "run_baseline",
    "run_baselines",
    "sample_community",
    "sample_candidate_nodes_by_community",
    "sample_node_from_community",
    "score_communities_by_size",
    "select_ml_candidate_nodes",
    "simulate_independent_cascade",
    "simulate_independent_cascade_once",
    "SUPPORTED_DIFFUSION_MODELS",
    "train_gnn_node_utility_model",
    "train_node_utility_model",
    "UnsupportedGraphTypeError",
    "validate_diffusion_model",
    "build_node2vec_cache_path",
    "generate_node2vec_embeddings",
    "transform_node2vec_embeddings",
    "generate_ris_guidance",
    "validate_communities",
    "validate_community_assignments",
    "generate_singleton_node_utility_labels",
    "verify_protected_groups",
    "verify_dataset_phase1",
]
