"""Fair Influence Maximization research package."""

from .baselines import BaselineResult, run_baseline, run_baselines
from .community_detection import (
    CommunityDetectionResult,
    CommunityQualityMetrics,
    CommunityStats,
    CommunityValidationReport,
    choose_communities,
    compute_community_quality_metrics,
    detect_communities,
    format_community_debug_report,
    get_community_stats,
    get_community_sizes,
    get_node_community,
    get_nodes_in_community,
    sample_community,
    sample_candidate_nodes_by_community,
    sample_node_from_community,
    score_communities_by_size,
    validate_communities,
    validate_community_assignments,
)
from .config import DatasetConfig
from .data_loader import (
    LoadedDataset,
    ProtectedGroupReport,
    format_phase1_report,
    load_dataset,
    resolve_builtin_dataset,
    verify_protected_groups,
    verify_dataset_phase1,
)
from .diffusion import DiffusionResult, simulate_independent_cascade, simulate_independent_cascade_once
from .evaluation import SeedSetEvaluation, compute_f_score, evaluate_seed_set
from .experiment_runner import ExperimentSettings, run_experiment, run_loaded_experiment
from .feature_extraction import compute_node_features, compute_structural_node_scores
from .fairness import (
    FairnessMetrics,
    compute_dcv,
    compute_normalized_group_spread,
    compute_soft_mf,
    compute_strict_mf,
    evaluate_fairness,
)
from .hybrid_optimizer import CandidateEvaluation, HybridOptimizationResult, HybridSIEAConfig, HybridSIEAOptimizer

__all__ = [
    "BaselineResult",
    "CandidateEvaluation",
    "CommunityDetectionResult",
    "CommunityQualityMetrics",
    "CommunityStats",
    "CommunityValidationReport",
    "DatasetConfig",
    "LoadedDataset",
    "ProtectedGroupReport",
    "choose_communities",
    "DiffusionResult",
    "detect_communities",
    "ExperimentSettings",
    "evaluate_seed_set",
    "FairnessMetrics",
    "SeedSetEvaluation",
    "compute_f_score",
    "compute_dcv",
    "compute_community_quality_metrics",
    "compute_node_features",
    "compute_normalized_group_spread",
    "compute_structural_node_scores",
    "compute_soft_mf",
    "compute_strict_mf",
    "evaluate_fairness",
    "format_phase1_report",
    "format_community_debug_report",
    "get_community_stats",
    "get_community_sizes",
    "get_node_community",
    "get_nodes_in_community",
    "HybridOptimizationResult",
    "HybridSIEAConfig",
    "HybridSIEAOptimizer",
    "load_dataset",
    "run_experiment",
    "run_loaded_experiment",
    "resolve_builtin_dataset",
    "run_baseline",
    "run_baselines",
    "sample_community",
    "sample_candidate_nodes_by_community",
    "sample_node_from_community",
    "score_communities_by_size",
    "simulate_independent_cascade",
    "simulate_independent_cascade_once",
    "validate_communities",
    "validate_community_assignments",
    "verify_protected_groups",
    "verify_dataset_phase1",
]
